title: "Nilakshâ€™s Math Blog"
description: "Rambalings of a PhD Student"
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM


header_pages:
  - about.md

github_username: banecane
